USE Progetto_Chat;

DROP TABLE IF EXISTS Utente;

CREATE TABLE Utente(
	utenteID INT PRIMARY KEY IDENTITY (1,1),
	nickname VARCHAR(30) NOT NULL UNIQUE,
	pass VARCHAR(50) NOT NULL,
	email VARCHAR(30) NOT NULL UNIQUE
);

SELECT * FROM Utente;